config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :questions do
    get 'toggle', to: 'questions#toggle_answered', as: :toggle
    collection do
      get :autocomplete
    end
    resources :answers
  end
  resources :diseases, except: [ :destroy ]
  resources :answers do
    member do
      put "like", to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
  get "user_home", to: "pages#user_home"
  resources :users
  get 'tags/:tag', to: 'questions#index', as: :tag
  # get "/questions/:id", to: "questions#mark_as_answered", as: :answered
  get 'my_question', to: "pages#my_question"

  resources :notifications, only: [:index] do
    post :mark_as_read, on: :collection
    post :mark_as_read, on: :member
  end
end

app/models/question.rb
class Question < ApplicationRecord
  searchkick language: "english", match: :word_start

  belongs_to :disease
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :user, presence: true
  acts_as_votable

  after_create :post_new_question
  acts_as_taggable

  def total_upvotes
    self.answers.pluck(:upvotes).sum
  end

  def self.top_9_questions(disease)
    disease.questions.sort_by do |question|
      -question.number_votes
    end.take(9)
  end

  def number_resolved(user)
    count = 0
    user.questions.each do |question|
      count += 1 if question.answered
    end
  end

  def number_unresolved(user)
    user.questions.count - number_resolved(user)
  end


  def number_votes
   answers = []
    self.answers.each do |answer|
      answers << answer.get_upvotes.size
    end
    return upvote = answers.sum
  end

  def useful?
    if number_votes > 1 # il faudra changer le 0 cest juste pour que le test soit plus easy
      return true
    else
      return false
    end
  end


  private

  def post_new_question
    # SlackPost.new.post_new_question(self).deliver
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_question, only: [ :show, :update, :destroy ]

  def index
    @questions = policy_scope(Question)
    #@questions = @questions.search params[:query], misspellings: {edit_distance: 1}
    @questions = if params[:query].present?
      Question.search(params[:query])
    elsif params[:tag].present?
      Question.tagged_with(params[:tag]).page(params[:page]).per(5)
    else
      Question.all.where(answered: false).page(params[:page]).per(5)
    end
  end

  def new
    @user = current_user
    @disease = current_user.disease_id
    @question = Question.new
    authorize @question
  end

  def create
    @disease = current_user.disease_id
    @question = Question.new(question_params)
    @question.disease = Disease.find(@disease)
    @question.user = current_user
    authorize @question
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @question = Question.find(params[:id])
    @disease = Disease.find(params[:disease_id])
  end

  def update
    # @disease = Disease.find(params[:disease_id])
    if params[:answered].present?
      @question.answered = params[:answered]
    else
      @question.update(question_params)
    end
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    # redirect to the index
    redirect_to questions_path
  end

  def toggle_answered
    @question = Question.find(params[:question_id])
    authorize @question
    @question.answered = !@question.answered

    if @question.save
      redirect_to question_path(@question)
    end
  end

  def autocomplete
    authorize Question.new

    questions = Question.search(params[:query], {
      fields: ["title^5", "body"],
      match: :word_start,
      limit: 10,
      misspellings: {below: 1}
    })
    render json: questions.map { |question| render_to_string( partial: 'questions/autocomplete', locals: { question: question }) }
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :disease_id, :user_id, :answered, :query, :tag_list)
  end

  def set_question
    @question = Question.find(params[:id])
    authorize @question
  end

end

app/views/questions/_autocomplete.html.erb
<div class="autocomplete-results">
  <%= question.title %>
</div>

app/views/questions/_index_card.html.erb
<div class="question-index-msg">
<a class="question-show" href="/questions/<%= question.id %>" ></a>
  <div class="question-index-avatar-title-tags">
    <div class="question-index-avatar">
      <%= cl_image_tag question.user.photo, crop: :fill, class: "avatar-question-card" %>
      <h5><%= question.user.firstname %></h5>
    </div>
    <div class="question-index-tags">
      <div id='tag_cloud'>
        <% tag_cloud question.tag_counts, %w{s m l} do |tag| %>
          <%= link_to tag.name, tag_path(tag.name)%>
        <% end %>
      </div>
    </div>
    <div class="question-index-title">
      <h4><%= question.title.capitalize %></h4>
    </div>
  </div>
  <div class="question-index-best-answer">
    <div class="question-index-announce-best-answer">
      <h4>Meilleure réponse</h4>
    </div>
    <div class="question-index-answer">
      <p>
        <% answers_sorted = question.answers.sort_by {|answer| -answer.get_upvotes.size} %>
        <% if answers_sorted.blank? %>
        <% else %>
          <%= answers_sorted.first.body  %>
        <% end %>
      </p>
    </div>
  </div>
  <div class="question-index-indicators">
    <div class="question-index-validation">
      <% if question.useful? %>
        <h5>SUPER QUESTION &nbsp;<i class="fas fa-rocket big-pink-icon"></i></h5>
      <% end %>
    </div>
    <div class="question-index-resolue">
      <%= render "questions/resolue", question: question %>
    </div>
  </div>
</div>

app/views/questions/_resolue.html.erb
<% if current_user == question.user %>
  <% if question.answered == false %>
    <%= link_to 'Résolue?', question_toggle_path(question), class: "btn-tertiary" %>
  <% else %>
    <h5> <i class="fas fa-crown big-blue-icon"></i> &nbsp; RÉSOLUE !</h5>
  <% end %>
<% else %>
  <% if question.answered == false %>
    <h5 class="h5-pink"><i id="need" class="fas fa-ambulance big-pink-icon"></i> &nbsp; BESOIN DE RÉPONSES !</h5>
  <% else %>
    <h5> <i class="fas fa-crown big-icon big-blue-icon"></i> &nbsp; RÉSOLUE !</h5>
  <% end %>
<% end %>

app/views/questions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="title">
        <h1>Questions & Réponses</h1>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="index-search-bar">
        <div class="row">
          <div class="col-xs-8 col-xs-offset-2">
            <div class="form-search">
              <span class="icon"><i class="fa fa-search"></i></span>
              <%= form_tag(questions_path, method: :get) do %>
                <%= text_field_tag :query, params[:query], class: 'form-control typeahead', id: "question_search", placeholder:"Recherche ta question" %>
                <%= submit_tag 'Shine' , class: 'search-btn shake-slow'  %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="filters">
        <h3>Filtres </h3>
          <ul class="list-inline">
            <li>
              <%= link_to "Top Questions", user_home_path, :class => "btn-tertiary" %>
            </li>
            <li>
              <%= link_to "Proposer des réponses", user_home_path, :class => "btn-tertiary" %>
            </li>
            <li>
              <%= link_to "Mes questions", my_question_path, :class => "btn-tertiary" %>
            </li>
          </ul>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-xs-12">
      <div class="ask-new-question">
        <%= link_to new_question_path do %>
          <li class="btn-big">Pose une nouvelle question</li>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="results">
      <% if @questions.blank? %>

        <div class="no-answer">
          <i class="fas fa-question-circle big-pink-icon"></i>
          <h3>Oups, aucune question en rapport avec "<%= params[:query] %>" ne semble exister.</h3>
          <h3>Pose ta question !</h3>
        </div>

      <% else %>
        <% @questions.each do |question| %>
          <%= render "questions/index_card", question: question %>
        <% end %>

        <div id="infinte-scrolling">
          <%= paginate @questions %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="background-img" style="  background-image: linear-gradient(-225deg, rgba(0,101,168,0.1) 0%, rgba(0,36,61,0.1) 50%), url('https://images.unsplash.com/photo-1520132108877-a600a22e602a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ce1e82f878196c13478fd45941b700b8&auto=format&fit=crop&w=1350&q=80');">
    <div class="form">
      <div class="form-title">
        <h2>Nouvelle question</h2>
      </div>

      <div class="form-content">
        <%= simple_form_for [@question] do |f| %>
          <%= f.input :title, label: 'Que veux-tu savoir?', placeholder: 'Ta question...' %>
          <%= f.input :body, label: 'Description', placeholder: 'Ajoute une description...' %>
            <div>
              <%= f.label :tag_list, 'Tags (utilise des virgules pour plusieurs tags):', class: "field"%>
              <%= f.text_field :tag_list, class: "form-control" %>
            </div>
          <%= f.button :submit, value: "Shine", class: "btn-form" %>
        <% end %>
      </div>
    </div>
</div>

app/views/questions/show.html.erb
<script type="text/javascript">
    (function(){
        function loadOwnpageScript(e){var t="https://script.ownpage.fr/v1/",a=document.createElement("script"),n=document.getElementsByTagName("script")[0];a.type="text/javascript",a.defer=1,a.async=1,a.src=t+"ownpage.js",a.onload=e,a.readyState?a.onreadystatechange=function(){("loaded"==a.readyState||"complete"==a.readyState)&&(a.onreadystatechange=null,e&&"function"==typeof e&&e())}:a.onload=function(){e&&"function"==typeof e&&e()},n.parentNode.insertBefore(a,n)}

        loadOwnpageScript(function () {
            Ownpage.trackPage('aeb86d31fc184897', "<%= current_user ? Digest::MD5.hexdigest(current_user.email) : nil %>" );
        });
    })();
</script>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="question-big-box">
        <div class="question-pic-name">
          <%= cl_image_tag @question.user.photo, crop: :fill, class: "avatar-question-card" %>
            <h5><%= @question.user.firstname %></h5>
        </div>

        <div class="question-msg-show">
          <div class="question-msg-show-title-validation">
            <div class="question-msg-show-title">
              <h4><%= @question.title.capitalize %></h4>
            </div>
            <div class="validation">
              <% if @question.useful? %>
                <h5>SUPER QUESTION &nbsp;<i class="fas fa-rocket big-blue-icon"></i></h5>
              <% end %>
            </div>
          </div>

          <div class="question-msg-show-details">
            <p>Détails: <%= @question.body.capitalize %></p>
          </div>
          <div class="question-msg-show-date">
            <p>Le <%= @question.created_at.strftime("%d/%m/%Y")%></p>
          </div>
          <div class="tag-and-resolue">
            <div id='tag_cloud'>
              <% tag_cloud @question.tag_counts, %w{s m l} do |tag| %>
                <%= link_to tag.name, tag_path(tag.name)%>
              <% end %>
            </div>
            <div class="resolue">
              <%= render "questions/resolue", question: @question %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="answers">
      <% @answers_sorted = @answers.sort_by {|answer| -answer.get_upvotes.size} %>
      <% @answers_sorted.each do |answer| %>
        <%= render "answers/show", answer: answer, top_answer: answer.top_answer %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="answer-form">
        <%= render 'answers/form', question: @question, answer: @answer %>
        <div id="infinte-scrolling">
          <%= paginate @answers %>
        </div>
      </div>
    </div>
  </div>
</div>



<!--
  <#% if policy(Answer).create? %>
    <#%= link_to "Rejoins la conversation avec ta réponse", new_question_answer_path(@question) %>
  <#% end %> -->