config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :questions do
    get 'toggle', to: 'questions#toggle_answered', as: :toggle
    collection do
      get :autocomplete
    end
    resources :answers
  end
  resources :diseases, except: [ :destroy ]
  resources :answers do
    member do
      put "like", to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
  get "user_home", to: "pages#user_home"
  resources :users
  get 'tags/:tag', to: 'questions#index', as: :tag
  # get "/questions/:id", to: "questions#mark_as_answered", as: :answered
  get 'my_question', to: "pages#my_question"

  resources :notifications, only: [:index] do
    post :mark_as_read, on: :collection
    post :mark_as_read, on: :member
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Shinier est fait avec <i class="fa fa-heart"></i> par notre équipe à Paris
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <% if user_signed_in? %>

    <div class="logo-box">
      <%= link_to user_home_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-shinier.svg", height: 50%>
        <p class="logo-name">Shinier</p>
      <% end %>
    </div>

  <% else %>

    <div class="logo-box">
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo-shinier.svg", height: 50 %>
        <p class="logo-name">Shinier</p>
      <% end %>
    </div>

  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <%= link_to "Poser une question", new_question_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Aider la communauté", questions_path, class: "navbar-wagon-item navbar-wagon-link" %>



      <%= link_to "Tableau de bord", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>

      <div class="navbar-wagon-item navbar-wagon-link" id="allo">
        <div class="dropdown">
          <div class="dropdown-toggle" data-toggle="dropdown">
            <% if current_user.notifications.where(read_at: nil).any? %>
                <i class="fas fa-bell shake bell-full-pink"></i>
                <span class="bell-full-pink"><%= current_user.notifications.where(read_at: nil).count %></span>
            <% else %>
              <i class="far fa-bell"></i>
            <% end %>
          </div>
          <% if current_user.notifications.where(read_at: nil).any? %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <% current_user.notifications.each do |notification| %>
                <% if notification.read_at.nil? %>
                  <li>
                    <div class="notification-inline">
                      <%= link_to "#{notification.actor.firstname} a repondu", question_path(notification.notifiable.question), class: "navbar-wagon-item navbar-wagon-link" %>
                      <%= link_to "lu?", mark_as_read_notification_path(notification), method: :post, class: "navbar-wagon-item navbar-wagon-link lu"%>
                    </div>
                  </li>
                <% end %>
              <% end %>
              <div>
               <%= link_to "Tout lu?", mark_as_read_notifications_path, method: :post, class: "tout-lu" %>
              </div>
            </ul>
          <% end %>
        </div>
      </div>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">

        <div class="dropdown">
          <%= cl_image_tag current_user.photo, height: 300, width: 400, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Mes questions", my_question_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Pathologie", disease_path(current_user.disease), class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Slack", "https://shinier.slack.com/messages/diabete/", target: "_blank", class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li>
              <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Inscription"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->

  <% if user_signed_in? %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Poser une question", diseases_path %></li>
          <li><%= link_to "Aider la communauté", questions_path%></li>
          <li><%= link_to "Pathologie", "#"%></li>
          <li><%= link_to user_path(current_user) do %><%= t(".profile", default: "Profile") %>
              <% end %></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %><%= t(".sign_out", default: "Déconnexion") %>
            <% end %></li>
        </ul>
      </div>
    </div>

  <% else %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to t(".sign_in", default: "Inscription"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_side_navbar.html.erb
 <div id="mySidenav" class="sidenav">
 <!--  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a> -->
  <a href="#">About</a>
  <a href="#">Services</a>
  <a href="#">Clients</a>
  <a href="#">Contact</a>
</div>

<!-- Use any element to open the sidenav -->
<!-- <span onclick="openNav()">open</span> -->

<!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->
<!-- <div id="main"> -->
<!--   ...
</div>  -->