config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :questions do
    get 'toggle', to: 'questions#toggle_answered', as: :toggle
    collection do
      get :autocomplete
    end
    resources :answers
  end
  resources :diseases, except: [ :destroy ]
  resources :answers do
    member do
      put "like", to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
  get "user_home", to: "pages#user_home"
  resources :users
  get 'tags/:tag', to: 'questions#index', as: :tag
  # get "/questions/:id", to: "questions#mark_as_answered", as: :answered
  get 'my_question', to: "pages#my_question"

  resources :notifications, only: [:index] do
    post :mark_as_read, on: :collection
    post :mark_as_read, on: :member
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  searchkick language: "english", match: :word_start
  belongs_to :question
  belongs_to :user

  validates :body, presence: true
  validates :user, presence: true
  acts_as_votable
  after_create :create_notifications

  def create_notifications
    recipient = self.question.user
    # answer_user = self.question.answers.map(&:user)
    if recipient != self.user
      Notification.create(recipient: recipient, actor: self.user, action: 'posted', notifiable: self)
    end
  end

  def top_answer
    question = self.question
    question_sorted = Answer.where(question: question).sort_by do |answer|
      -answer.get_upvotes.size
    end
    question_sorted.first == self
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController


  def index
    # should implement the way how the answer will be display
  end


  def new
    @user = current_user
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    authorize @answer
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.user = current_user
    @answer.question = @question
    authorize @answer
    if @answer.save
      respond_to do |format|
        format.html { redirect_to question_path(@question) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def show
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    authorize @answer
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
    authorize @answer
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.update(answer_params)
    authorize @answer
    if @answer.save
      #redirect somewhere
    else
      render :new
    end
  end

  def destroy
    @answer = Answer.find(params[:id].to_i)
    authorize @answer
    @answer.destroy
    redirect_to question_answers_path
  end

  def upvote
    @answer = Answer.find(params[:id])
    authorize @answer
    if @answer.upvote_by current_user
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path }
        format.js
      end
    end
  end

  def downvote
    @answer = Answer.find(params[:id])
    authorize @answer
    if @answer.downvote_by current_user
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path }
        format.js
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :user_id, :question_id)
  end

end

app/views/answers/_counter.html.erb
<div>
  <div><%= answer.get_upvotes.size %></div>
  <%= link_to like_answer_path(answer), method: :put, remote: true do %>
    <div tooltip = "Cliquez si cette réponse vous a été utile !"><i class="<%= current_user&.voted_for?(answer) ? "fa" : "far" %> fa-heart big-icon shake"></i>
    </div>
  <% end %>
</div>

app/views/answers/_form.html.erb
  <%= simple_form_for [question, answer], remote: true do |f| %>
    <div class="answer-new-form">
      <%= f.input :body, label: false, placeholder: 'Et toi, quelle est ta réponse ?', input_html: { class: "answer-form-new", rows: 3}  %>
      <%= f.button :submit, "Ajoute ta réponse", class: "btn-answer-new" %>
    </div>
  <% end %>

app/views/answers/_show.html.erb
<% if answer.get_downvotes.size < 2  %>
  <div class="col-xs-10 col-xs-offset-1">
    <div class="question-big-box">
      <div class="question-msg-show">
        <div class="answer-details-upvotes">
          <div class="upvotes" data-answer-id="<%= answer.id %>" >
            <div class="counter">
              <%= render "answers/counter", answer: answer %>
            </div>
          </div>
          <div class="answer-details">
          <% if answer.top_answer %>
            <div class="top">
              <h5>TOP RÉPONSE</h5>
            </div>
          <% end %>
            <div class="answer-msg-show-body">
              <p><%= answer.body %></p>
            </div>
            <div class="question-msg-show-date">
              <p>Le <%= answer.created_at.strftime("%d/%m/%Y") %></p>
            </div>
            <div class="question-msg-show-report">
              <h6><%= link_to "Cette réponse te paraît inappropriée?", dislike_answer_path(answer), method: :put %></h6>
            </div>
          </div>
        </div>
      </div>
      <div class="question-pic-name">
        <%= cl_image_tag answer.user.photo, crop: :fill, class: "avatar-question-card" %>
        <h5><%= answer.user.firstname %></h5>
        <% if current_user&.slack_id %>
        <p><%= link_to "Contact this user", "https://shinier.slack.com/messages/#{current_user&.slack_id}/", target: "_blank" %></p>
        <% else %>
          <p><%= link_to "Contact this user", "https://shinier.slack.com/messages/diabete/", target: "_blank" %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/answers/create.js.erb
function refreshForm(innerHTML) {
  const newAnswerForm = document.getElementById('new_answer');
  newAnswerForm.innerHTML = innerHTML;
}

function addAnswer(reviewHTML) {
  const answers = document.querySelector(".answers");
  answers.insertAdjacentHTML('afterbegin', reviewHTML);
}

<% if @answer.errors.any? %>
  refreshForm('<%= j render "answers/form", question: @question, answer: @answer %>');
<% else %>
  addAnswer('<%= j render "answers/show", answer: @answer %>');
  refreshForm('<%= j render "answers/form", question: @question, answer: Answer.new %>');
<% end %>

app/views/answers/new.html.erb
<div class="form">
  <div class="form-title">
    <h1>Answer new</h1>
  </div>

  <div class="form-table">
    <%= simple_form_for [@question, @answer] do |f| %>
      <%= f.input :body, placeholder: 'What is your answer' %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/answers/show.html.erb
<%= @answer.body %>
<%= @answer.get_upvotes.size %>
<%= link_to "Useful", like_answer_path(@answer), method: :put %>
<%= link_to "Report", dislike_answer_path(@answer), method: :put %>

app/views/answers/upvote.js.erb
// select the arrow , and change it to another class
function refreshUpvote(olderClass, newClass) {
  const newUpvote = document.querySelectorAll('[data-answer-id="<%= @answer.id %>"]');
  newUpvote.forEach((upvote) => {
    console.log("titi", upvote.querySelector(".big-icon"))
    upvote.querySelector(".big-icon").classList.replace(olderClass, newClass)
  })
}

// select the counter and update it
function addUpvote(newCounter) {
  const upvotes = document.querySelectorAll('[data-answer-id="<%= @answer.id %>"]');
  upvotes.forEach((upvote) => {
    upvote.querySelector(".counter").innerHTML = newCounter
  })
}

addUpvote('<%= j render "answers/counter", answer: @answer %>')